### ISSUE TITLE
Hot reload not working for stateless components

### ISSUE THREAD

**Issue by pulse00** [geowarin/boot-react#13]
Thanks for this repo, it helped a lot getting started with setting up spring and react!

Here's a question though: When running the frontend app using `npm start`, hot module replacement does not work when editing UI components:

```
process-update.js:59 [HMR] The following modules couldn't be hot updated: (Full reload needed)
 - ./src/ui/Component.js
```

Is this a known issue in this starter app?

**Comment by geowarin** [comment]
Yes, unfortunately, stateless functional components are not yet supported by the react transform plugin...
The workaround is to create good old components extending `React.Component``

Change this:
```
export const MyComponent = (props) => {
...
}
```

to this:

```
export class MyComponent extends React.Component {

  render() {
...
  }
}
```
See:
https://github.com/gaearon/babel-plugin-react-transform/issues/57

This is unfortunate since functional component are really awesome

**Comment by pulse00** [comment]
I see, thanks for pointing to this issue.

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61
