### ISSUE TITLE
support bootstrap

### ISSUE THREAD

**Issue by mtiger2k** [geowarin/boot-react#20]
Could you please add support for bootstrap and css? Thanks.

**Comment by geowarin** [comment]
Hi @mtiger2k,

The project has support for [stylus](http://stylus-lang.com/), which allows loading any css.
Have a look at [main.styl](https://github.com/geowarin/boot-react/blob/master/frontend/assets/stylus/main.styl#L5) which loads the purecss stylesheets.

You can do the same with bootstrap by installing it with npm and importing it with something like:

```
@import '~boostrap/dist/main.css'
```

If you want to use pure css and not stylus (IMHO, you shouldn't, stylus is a superset of CSS so there is no downside using it), you can remove the `stylus-loader` from the webpack configurations.

I think pure css is simpler and more lightweight than bootstrap (essentially because you don't need jquery and the like to make it work). That's why I went with pure CSS.

You can have a look at [react-boostrap](https://react-bootstrap.github.io/), it shouldn't be too hard to integrate it.
